/**
 * Stage 4 — Verify determinism.
 *
 * Re-runs normalization and Dart generation into a scratch directory and diffs
 * the result against the committed artifacts. Any difference exits non-zero so
 * CI fails on a dirty diff. Re-running from the same source lock must be
 * byte-identical.
 *
 * The generation check only needs the committed normalized snapshot, so it runs
 * in CI without installing the upstream npm packages. The normalization check
 * additionally runs when `build/raw-tokens.json` is present (i.e. after a fresh
 * `extract`).
 *
 * Run:  node tool/verify_generated.mjs
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, existsSync, readdirSync, mkdtempSync, rmSync, cpSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoTokens = join(__dirname, 'tokens', 'carbon-tokens.normalized.json');
const generatedDir = join(__dirname, '..', 'lib', 'src', 'tokens', 'generated');

let failures = 0;
function fail(msg) {
  console.error(`  ✗ ${msg}`);
  failures += 1;
}
function ok(msg) {
  console.log(`  ✓ ${msg}`);
}

// --- 1. Generation is deterministic from the committed snapshot ---
{
  const scratch = mkdtempSync(join(tmpdir(), 'carbon-verify-'));
  try {
    // Mirror the tool dir so generate writes to a throwaway package location.
    const toolCopy = join(scratch, 'tool');
    cpSync(__dirname, toolCopy, {
      recursive: true,
      filter: (src) => !src.includes('node_modules') && !src.includes(`${join('tool', 'build')}`),
    });
    // Regenerate into scratch/lib/src/tokens/generated by running the emitter
    // with a redirected output. The emitter computes outDir relative to itself.
    execFileSync('node', [join(toolCopy, 'generate_tokens.mjs')], { stdio: 'pipe' });
    const regenDir = join(scratch, 'lib', 'src', 'tokens', 'generated');

    const committed = readdirSync(generatedDir).filter((f) => f.endsWith('.g.dart')).sort();
    const regen = readdirSync(regenDir).filter((f) => f.endsWith('.g.dart')).sort();
    if (committed.join(',') !== regen.join(',')) {
      fail(`generated file set differs:\n    committed: ${committed}\n    regen:     ${regen}`);
    }
    for (const file of committed) {
      const a = readFileSync(join(generatedDir, file), 'utf8');
      const b = existsSync(join(regenDir, file)) ? readFileSync(join(regenDir, file), 'utf8') : '';
      if (a !== b) fail(`generated ${file} is not byte-identical to a fresh regeneration`);
    }
    if (!failures) ok(`all ${committed.length} generated Dart files are reproducible from the snapshot`);
  } finally {
    rmSync(scratch, { recursive: true, force: true });
  }
}

// --- 2. Generated files carry provenance and no unparsed CSS units ---
{
  const cssUnit = /\b\d+(?:\.\d+)?(rem|vw|em)\b|cubic-bezier|rgba?\(/;
  for (const file of readdirSync(generatedDir).filter((f) => f.endsWith('.g.dart'))) {
    const text = readFileSync(join(generatedDir, file), 'utf8');
    if (!text.includes('SPDX-License-Identifier: Apache-2.0')) {
      fail(`${file} is missing SPDX license provenance`);
    }
    if (!text.includes('IBM Carbon')) {
      fail(`${file} is missing Carbon source attribution`);
    }
    // Ignore comment/doc lines; only code lines must be free of raw CSS units.
    const codeLines = text.split('\n').filter((l) => !l.trimStart().startsWith('//'));
    const offender = codeLines.find((l) => cssUnit.test(l));
    if (offender) fail(`${file} contains an unparsed CSS unit/expression: ${offender.trim()}`);
  }
  if (!failures) ok('every generated file carries provenance and contains no unparsed CSS');
}

// --- 3. Normalization is deterministic (only when raw extract is present) ---
{
  const rawPath = join(__dirname, 'build', 'raw-tokens.json');
  if (existsSync(rawPath)) {
    const before = readFileSync(repoTokens, 'utf8');
    execFileSync('node', [join(__dirname, 'normalize_tokens.mjs')], { stdio: 'pipe' });
    const after = readFileSync(repoTokens, 'utf8');
    if (before !== after) {
      fail('normalized snapshot changed on re-normalization (non-deterministic or stale)');
    } else {
      ok('normalized snapshot is reproducible from build/raw-tokens.json');
    }
  } else {
    console.log('  · skipped normalization check (no build/raw-tokens.json; run extract first)');
  }
}

if (failures) {
  console.error(`\nverify: FAILED (${failures} problem${failures === 1 ? '' : 's'})`);
  process.exit(1);
}
console.log('\nverify: OK — token generation is deterministic and provenance is intact');
