dart_code_metrics:
  extends:
    - package:dart_code_metrics_presets/recommended.yaml
    - package:dart_code_metrics_presets/metrics_recommended.yaml
  metrics-exclude:
    - test/**
  rules-exclude:
    - test/**
  rules:
    # avoid-collection-mutating-methods: true
    newline-before-return: true
    avoid-importing-entrypoint-exports:
      only-in-src: true
    prefer-match-file-name: false
    avoid-suspicious-super-overrides: false
    prefer-overriding-parent-equality: false
    prefer-correct-callback-field-name: false
    prefer-single-widget-per-file: false
    match-getter-setter-field-names: false
    prefer-dedicated-media-query-methods: false
    avoid-shadowing: false
    enum-constants-ordering: false
    avoid-unsafe-collection-methods: false
    prefer-prefixed-global-constants: false
    avoid-returning-widgets: false
    avoid-unnecessary-overrides: false
    arguments-ordering:
      first:
        - key
        - spec
      last:
        - child
        - children
    avoid-nested-conditional-expressions:
      acceptable-level: 3
    member-ordering:
      order:
        - public-fields
        - private-fields
        - constructors
        - static-methods
        - private-methods
        - private-getters
        - private-setters
        - public-getters
        - public-setters
        - public-methods
        - overridden-public-methods
        - overridden-public-getters
        - build-method
    prefer-named-boolean-parameters:
      ignore-single: true
analyzer:
  errors:
    non_constant_identifier_names: ignore

linter:
  rules:
    # TODO: Turn this to true when all public apis are documented 
    public_member_api_docs: false
    prefer_relative_imports: true