"""Generate an offline-first catalog from the canonical manifest and real paths."""
from pathlib import Path
import json,html
from source.restrictions import load_restrictions, effective_catalog, usage_text
ROOT=Path(__file__).resolve().parents[1]
CATEGORIES={'navigation':'Navigation','actions':'Actions','content':'Content','people-communication':'People & communication','status-security':'Status & security','system-data':'System & data','media':'Media','commerce-location':'Commerce & location'}

def build_catalog(catalog,paths,svg_text):
    restrictions=load_restrictions(ROOT)
    catalog=effective_catalog(catalog,restrictions)
    restriction_summary=usage_text(restrictions['warning-visible-label'])
    e=html.escape; items=catalog['icons'];groups=[g for g in CATEGORIES if any(i['category']==g for i in items)]
    def svg(id,a='outline',n=24,css=None):
        css=css or n
        return f'<svg xmlns="http://www.w3.org/2000/svg" width="{css}" height="{css}" viewBox="0 0 {n} {n}" fill="currentColor" fill-rule="evenodd" aria-hidden="true" focusable="false"><path d="{paths[id][a][str(n)]}"/></svg>'
    def pair(id,n=24,css=None,labels=True):
        return ''.join('<div class="pair-member">'+svg(id,a,n,css)+(f'<small>{a.upper()}</small>' if labels else '')+'</div>' for a in ['outline','filled'])
    def size_options(default=24,only_native=False):
        return ''.join(f'<option value="{s}"'+(' selected' if s==default else '')+f'>{s} px</option>' for s in ([12,16,24] if only_native else [12,14,16,20,24,32]))
    themes='<option value="light">Off-white</option><option value="dark">Dark</option><option value="lime">Lime</option><option value="cobalt">Cobalt</option>'
    cards=[];examples=[]
    for g in groups:
        member=[i for i in items if i['category']==g];cg=[];eg=[]
        for m in member:
            id=m['id'];new=m['stage']=='pilot-addition'
            masters=''.join(f'<div><span>{n} px</span><div class="master-pair">{svg(id,"outline",n)}{svg(id,"filled",n)}</div></div>' for n in [12,16,24])
            cg.append(f'<button type="button" class="icon-card" data-icon="{id}" aria-label="Inspect {e(m["label"])}"><div class="card-head"><strong>{e(m["label"])}</strong><span class="tag {"new" if new else ""}">{"NEW" if new else "LOCKED"}</span></div><div class="pair card-live" data-icon="{id}">{pair(id,24,32)}</div><div class="master-strip">{masters}</div></button>')
            lines=''.join(f'<div class="example-line"><span>{a.upper()}</span><button type="button" class="sample-control" data-icon="{id}" data-appearance="{a}"><span class="example-icon">{svg(id,a,16)}</span><span>{e(m["example"])}</span></button></div>' for a in ['outline','filled'])
            eg.append(f'<article class="example-card" data-example="{id}"><h3>{e(m["label"])}</h3>{lines}</article>')
        cards.append(f'<section class="family" id="family-{g}" data-category="{g}"><div class="family-head"><h3>{CATEGORIES[g]}</h3><span>{len(member):02} CONCEPTS / {len(member)*6:03} DRAWINGS</span></div><div class="cards">'+''.join(cg)+'</div></section>')
        examples.append(f'<div class="family-head"><h3>{CATEGORIES[g]}</h3><span>ONE LABELED EXAMPLE PER APPEARANCE</span></div><div class="example-grid">'+''.join(eg)+'</div>')
    chips=''.join(f'<a href="#family-{g}">{CATEGORIES[g]} <b>{sum(i["category"]==g for i in items)}</b></a>' for g in groups)
    opts=''.join(f'<option value="{g}">{CATEGORIES[g]}</option>' for g in groups)
    rows=[]
    for m in items:
        cells=''.join(f'<td><div class="mini-pair">{svg(m["id"],"outline",12 if s<=12 else 16 if s<=16 else 24,s)}{svg(m["id"],"filled",12 if s<=12 else 16 if s<=16 else 24,s)}</div></td>' for s in [12,14,16,20,24,32])
        rows.append(f'<tr data-matrix="{m["id"]}"><td>{e(m["label"])}</td>{cells}</tr>')
    def app(theme):
        controls=''.join(f'<button class="icon-button demo-action" type="button" aria-label="{label}">{svg(id,"outline",16)}</button>' for id,label in [('edit','Edit details'),('filter','Filter results'),('sliders','Adjust view'),('gear','General settings')])
        return f'''<article class="app surface" data-theme="{theme}"><div class="eyebrow">EXAMPLE INTERFACE / {theme.upper()}</div><div class="app-head"><h3>Project workspace</h3><button class="icon-button favorite-toggle" type="button" aria-label="Favorite project" aria-pressed="false">{svg('star')}</button></div><div class="app-bar"><button class="action-primary demo-action" type="button">{svg('plus','filled',16)}Create item</button>{controls}</div><div class="app-row">{svg('file','outline',16)}<span>Interface specification</span><small>16 px</small></div><div class="app-row">{svg('calendar','outline',16)}<span>Review scheduled</span><small>16 px</small></div><div class="app-row">{svg('info','outline',12)}<span>Updated just now</span><small>12 px + label</small></div><div class="app-bar"><button class="demo-action" type="button">{svg('save','outline',16)}Save changes</button><button class="demo-action" type="button">{svg('help','outline',16)}Help</button></div></article>'''
    notes=[]
    for m in items:
        notes.append(f'<details data-review="{m["id"]}"><summary>{e(m["label"])} — {"preserved baseline" if m["stage"]=="baseline" else "pilot addition"}</summary><div><p><strong>{e(m["meaning"])}</strong></p><p>{e(m["review"]["note"])}</p><p>{e(m["review"]["usage"])}</p><p class="muted">Pair model: {m["pairModel"]}. Independent design approval: pending. Recognition: not user-tested.</p></div></details>')
    css=(ROOT/'source/web/catalog.css').read_text();js=(ROOT/'source/web/catalog.js').read_text()
    # JSON block is safe even after a catalog author adds literal HTML syntax.
    data=json.dumps({'catalog':catalog,'paths':paths,'restrictions':restrictions},separators=(',',':')).replace('<','\\u003c').replace('>','\\u003e').replace('&','\\u0026')
    page=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="48 Angular icons. Outline and filled, three native optical masters, complete examples and review notes."><title>Vector UI — Angular 48 pilot</title><style>{css}</style></head><body>
<a class="skip" href="#catalog">Skip to icon catalog</a><div class="wrap"><header><div class="brand">VECTOR UI</div><div class="eyebrow right">ANGULAR / PILOT 48<br>0.5.0-PILOT.2</div></header>
<div class="hero"><div><div class="eyebrow">AN ICON FAMILY, NOT A FOLDER OF SYMBOLS</div><h1>ANGULAR / 48</h1><p>One visual language. Outline and filled. Drawn for real interface sizes. The original 33 icons stay locked; 15 new concepts extend the family.</p></div><aside class="hero-status"><div class="status-line">PRIVATE PILOT / REVIEW BUILD</div><div class="stats"><div><strong>48</strong><span>ICONS</span></div><div><strong>2</strong><span>APPEARANCES</span></div><div><strong>288</strong><span>NATIVE SVGs</span></div></div><p>12 / 16 / 24 px optical masters. Angular is the only available style pack. Rounded is not drawn.</p></aside></div>
<nav class="nav" aria-label="Guide sections"><a href="#catalog">01 Catalog</a><a href="#interface">02 Interface</a><a href="#examples">03 Every icon in use</a><a href="#sizes">04 Size matrix</a><a href="#validation">05 Validation & rules</a></nav>
<noscript><p class="no-script">All icons, native pairs, examples, and review notes are shown below. Enable JavaScript for search, the inspector, and downloads.</p></noscript>
<section id="catalog"><div class="section-head"><h2><span class="num">01</span>Complete icon catalog</h2><span id="count" class="eyebrow" role="status">48 of 48 icons shown</span></div><p class="intro">Select a card to inspect its actual paths or download a native SVG. The main pair starts at 32 px display size; the three smaller pairs are native drawings at actual size.</p><div class="controls js-controls"><label><span>Search concepts or keywords</span><input type="search" id="search" placeholder="Try settings, help, arrow…" autocomplete="off"></label><label><span>Category</span><select id="category"><option value="">All categories</option>{opts}</select></label><label><span>Display size</span><select id="display-size">{size_options(32)}</select></label><label><span>Surface</span><select id="theme">{themes}</select></label><button type="button" id="new-only" aria-pressed="false">New 15 only</button></div><div class="chips">{chips}<button type="button" class="js-only" id="reset">Reset filters</button></div><div class="empty" id="empty"><p>No matching icons. Nothing has been substituted.</p><button id="empty-reset" type="button">Show all icons</button></div><div id="library" class="surface" data-theme="light">{''.join(cards)}</div><p id="size-note" class="toolbar-note">32 px display uses the 24 px optical master. Native strips below each card do not change.</p></section>
<section id="interface"><div class="section-head"><h2><span class="num">02</span>Interface, not just artwork</h2><span class="eyebrow">REAL SVGs / FIXED CONTROL SIZES</span></div><p class="intro">Small metadata uses 12 px icons with text. Toolbar icons sit inside larger controls. Favorite is a working outline/filled toggle; other buttons are explicitly labeled demo actions.</p><div class="workbench">{app('light')}{app('dark')}</div><p class="feedback" role="status" id="app-feedback">Interface examples only. No files or account settings are changed.</p></section>
<section id="examples"><div class="section-head"><h2><span class="num">03</span>Every icon in context</h2><span class="eyebrow">96 LABELED EXAMPLES / ALL 48 CONCEPTS</span></div><p class="intro">Each concept appears once in outline and once in filled form. Names describe glyphs; control labels describe actions. Search keywords do not become API aliases.</p><div class="context-controls js-only"><label><span>Example size</span><select id="example-size">{size_options(16)}</select></label><label><span>Example surface</span><select id="example-theme">{themes}</select></label></div><div class="surface" data-theme="light" id="examples-surface">{''.join(examples)}</div><p id="example-feedback" class="feedback" role="status">These are labeled action specimens, not a live product.</p></section>
<section id="sizes"><div class="section-head"><h2><span class="num">04</span>Size matrix</h2><span class="eyebrow">OUTLINE LEFT / FILLED RIGHT</span></div><p class="intro">12, 16, and 24 px are independent native masters. 14, 20, and 32 px are scaled previews. At 100% browser zoom the symbols below display at the labeled CSS sizes.</p><div class="matrix-wrap" role="region" aria-label="All icon sizes, scroll horizontally on narrow screens" tabindex="0"><table><thead><tr><th scope="col">Icon</th>{''.join(f'<th scope="col">{s} px<br><small>{"NATIVE" if s in [12,16,24] else "SCALED"}</small></th>' for s in [12,14,16,20,24,32])}</tr></thead><tbody>{''.join(rows)}</tbody></table></div></section>
<section id="validation"><div class="section-head"><h2><span class="num">05</span>Separate checks. Visible limits.</h2><span class="eyebrow">NO BLANKET QUALITY SCORE</span></div><div class="gate-grid"><article class="gate"><strong>TECHNICAL</strong><h3>Repeatable validation</h3><p>Matrix, schemas, path safety, baseline hashes, geometry, exports, and rebuild checks. Current results are in the package reports.</p></article><article class="gate"><strong>OPTICAL</strong><h3>Local review evidence</h3><p>Native-size drawings and critical gaps inspected. Original artwork preserved. Independent design approval is still pending.</p></article><article class="gate"><strong>INTERFACE</strong><h3>Real browser checks</h3><p>Test scopes include URL/file loading, layout, downloads, focus, and toggles. A test being present is not a pass; actual browser results and limits are recorded in reports.</p></article><article class="gate"><strong>RECOGNITION</strong><h3>Not user-tested</h3><p>No recognition score is claimed. Warning, Branch, Focus, and Help need labeled context in dense interfaces.</p></article></div>
<div class="rules"><article class="rule"><h3>Shared grammar, not identical bounding boxes</h3><p>Square terminals, deliberate diagonals, and nominal 1 / 1.5 / 2 px outlines. Dense icons can occupy smaller fields. Open symbols use regular/heavier pairs.</p></article><article class="rule"><h3>Size is part of the design</h3><p>Use the 12 px master up to 12 px, the 16 px master at 14–16 px, and the 24 px master from 20 px. Below 12 px is not reviewed. Intermediate sizes can soften pixel alignment.</p></article><article class="rule"><h3>One identity for each concept</h3><p>Sliders adjusts parameters. Filter narrows results. Gear opens settings. “Settings” is a search keyword, not a renamed Sliders API.</p></article><article class="rule"><h3>A component owns its accessible name</h3><p>Hide decorative inner SVGs from assistive technology and label the button. Selected state changes aria-pressed without changing the action name. Color alone is not the meaning.</p></article></div>
<div class="decisions"><strong>Known exception carried forward</strong>Warning’s outline mark-to-frame gaps are approximately 0.50 / 1.03 / 1.58 px at 12 / 16 / 24 px. These miss the general targets of 1 / 1.5 / 2 px. The artwork is preserved. {e(restriction_summary)} Filled 16/24 px negative punctuation also has a documented below-target width. Named ownership and independent approval remain pending.</div>
<div class="section-head"><h2>Decision for every icon</h2><button type="button" class="js-only" id="expand-notes" aria-expanded="false" aria-controls="notes">Expand review notes</button></div><div id="notes" class="review-notes">{''.join(notes)}</div>
<div class="decisions"><strong>Release boundary</strong>This pilot contains 48 drawn icons. The remaining 72 Core proposals and the Rounded pack are not represented as available. The distribution license is BSD 3-Clause, copyright Leo Farias. Public naming, maintainer approval, and user-recognition work remain open. No repository or package has been published.</div></section>
<footer><div>VECTOR UI / WORKING NAME<br>ANGULAR PILOT 0.5.0-PILOT.2</div><div>33 PRESERVED + 15 NEW / 288 SVG DRAWINGS<br>PRIVATE REVIEW BUILD — BSD-3-CLAUSE, LEO FARIAS</div></footer></div>
<dialog id="inspector" aria-labelledby="inspect-title"><div class="dialog-head"><div><div class="eyebrow" id="inspect-code-name">angular / sliders</div><h2 id="inspect-title">Sliders</h2></div><button id="inspect-close" type="button" aria-label="Close inspector">Close</button></div><div class="dialog-controls"><label><span>Native master</span><select id="inspect-size">{size_options(24,True)}</select></label><label><span>Inspection scale</span><select id="inspect-zoom"><option value="1">Actual size</option><option value="4" selected>4× geometry</option></select></label></div><div id="inspect-stage" class="surface inspect-stage" data-theme="light"><div class="pair" id="inspect-pair"></div></div><p class="toolbar-note" id="inspect-meta"></p><button id="inspect-grid" type="button" aria-pressed="false">Coordinate grid</button><p id="grid-legend" class="toolbar-note">One grid unit = one native coordinate. Dashed inset: reference keyline, not required artwork bounds. Center cross: canvas center.</p><div id="native-proof" class="surface native-proof" data-theme="light"><h3>Native raster proof</h3><p class="toolbar-note" id="native-proof-note">Actual-size raster, separate from the enlarged vector view.</p><div id="native-proof-pair" class="native-proof-pair"></div></div><p class="inspect-note" id="inspect-note"></p><p class="inspect-note" id="inspect-usage"></p><div class="download-row"><button type="button" data-download="outline">Download outline SVG</button><button type="button" data-download="filled">Download filled SVG</button></div><label><span>SVG source appearance</span><select id="code-appearance"><option>outline</option><option>filled</option></select></label><label><span>Native SVG code</span><textarea id="code" readonly spellcheck="false"></textarea></label><div class="download-row"><button type="button" id="copy-svg">Copy SVG</button></div><p id="copy-status" role="status" class="toolbar-note"></p></dialog>
<script type="application/json" id="icon-data">{data}</script><script>{js}</script></body></html>'''
    (ROOT/'docs/catalog/index.html').write_text(page,encoding='utf-8')
    # A lightweight proof sheet with actual native SVGs for deterministic browser capture.
    for mode in ('all','new'):
        chosen=[m for m in items if mode=='all' or m['stage']=='pilot-addition']
        body=''.join(f'<div class="proof-card"><strong>{e(m["label"])}</strong><span class="tag">{"NEW" if m["stage"]=="pilot-addition" else "LOCKED"}</span><div class="pair">{pair(m["id"],24,48)}</div><div class="master-strip">'+''.join(f'<div>{n} px<div class="master-pair">{svg(m["id"],"outline",n)}{svg(m["id"],"filled",n)}</div></div>' for n in [12,16,24])+'</div></div>' for m in chosen)
        sheet=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Angular {mode} proof</title><style>{css}.proof-grid{{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));border-top:1px solid var(--line);border-left:1px solid var(--line)}}.proof-card{{padding:20px;border-right:1px solid var(--line);border-bottom:1px solid var(--line)}}.proof-card strong{{font-size:13px}}.proof-card .tag{{float:right}}.proof-card .pair{{height:105px}}.proof-card .master-strip{{padding-top:15px}}.proof-grid .proof-card:last-child{{border-bottom:1px solid var(--line)}}@media(max-width:600px){{.proof-grid{{grid-template-columns:1fr 1fr}}}}</style></head><body><main class="wrap"><header><div class="brand">VECTOR UI</div><span class="eyebrow">ANGULAR / PILOT 48</span></header><div class="section-head" style="padding-top:24px"><h1>{"The complete 48-icon family" if mode=="all" else "The 15 pilot additions"}</h1><span class="eyebrow">OUTLINE / FILLED<br>ACTUAL NATIVE PAIRS BELOW</span></div><div class="proof-grid">{body}</div><footer>Large pairs show the 24 px master at 48 px. Lower pairs show native 12, 16, and 24 px. Review build, not recognition testing.</footer></main></body></html>'''
        (ROOT/f'docs/catalog/proof-{mode}.html').write_text(sheet)
