"""One source for size-aware usage rules and their generated presentations."""
from __future__ import annotations
import copy
import json
from pathlib import Path


def load_restrictions(root: Path) -> dict:
    data = json.loads((root / 'catalog/restrictions.json').read_text(encoding='utf-8'))
    records = data['records']
    if data['schemaVersion'] != 1 or len({r['id'] for r in records}) != len(records):
        raise ValueError('Invalid restriction registry')
    if len({(r['icon'], r['pack']) for r in records}) != len(records):
        raise ValueError('One consolidated restriction record is required per icon and pack')
    for record in records:
        if record['pack'] != 'angular' or set(record['sizes']) != {'12', '16', '24'}:
            raise ValueError('Incomplete restriction size matrix')
        for master, appearances in record['sizes'].items():
            if set(appearances) != {'outline', 'filled'}:
                raise ValueError('Incomplete restriction appearance matrix')
            for appearance, cell in appearances.items():
                if type(cell['visibleLabelRequired']) is not bool:
                    raise ValueError('Label requirement must be explicit')
                if len(cell['geometrySha256']) != 64:
                    raise ValueError('Restriction must identify its artwork')
    return {record['id']: record for record in records}


def usage_text(record: dict, native_size: int | None = None) -> str:
    sizes = [str(native_size)] if native_size is not None else sorted(record['sizes'], key=int)
    # Build prose from the same cells that power the inspector and API metadata.
    descriptions = []
    for appearance in ('outline', 'filled'):
        required = [size for size in sizes if record['sizes'][size][appearance]['visibleLabelRequired']]
        if required:
            descriptions.append(f"{appearance} at {' / '.join(required)} px")
    if not descriptions:
        return 'No additional visible-label restriction is recorded for this drawing.'
    return ('Visible text label required for ' + ' and '.join(descriptions)
            + '. This also applies to scaled uses of those masters. A tooltip or accessible name alone does not replace the visible label.')


def effective_catalog(catalog: dict, restrictions: dict) -> dict:
    result = copy.deepcopy(catalog)
    for icon in result['icons']:
        ref = icon['review'].get('usageRestriction')
        if ref:
            record = restrictions[ref]
            if record['icon'] != icon['id']:
                raise ValueError('Restriction belongs to a different icon')
            icon['review']['usage'] = usage_text(record)
    return result


def write_usage_outputs(root: Path, catalog: dict, restrictions: dict) -> None:
    """Generate optical notes and API guidance. Do not hand-edit their prose."""
    effective = effective_catalog(catalog, restrictions)
    notes = ['# Per-icon local review', '',
             '<!-- GENERATED by source/restrictions.py; edit catalog metadata instead. -->', '',
             'Local review only. Not independent approval or user-recognition testing.', '']
    for icon in effective['icons']:
        notes += [f"## {icon['label']}", '', icon['review']['note'], '', icon['review']['usage'], '']
    (root / 'docs/OPTICAL-REVIEW.md').write_text('\n'.join(notes), encoding='utf-8')
    lines = ['# Size-aware usage restrictions', '',
             '<!-- GENERATED; authoritative input: catalog/restrictions.json -->', '',
             'The same record drives catalog notes, the inspector, and the JavaScript usage helper.',
             'Geometry hashes refer to the exact standalone SVG bytes. Null owner/reviewer fields remain release blockers.', '',
             '```js', 'import {getIconUsage} from "./packages/web/index.mjs";',
             'const usage = getIconUsage("warning", {appearance: "filled", size: 20});',
             '// size 20 selects master 24; usage.visibleLabelRequired === true',
             '```', '',
             'The helper reports restrictions. It cannot enforce the surrounding interface text.',
             'An accessible name or tooltip is not a substitute for a visible text label.', '']
    data = {}
    for record in restrictions.values():
        data[record['icon']] = record
        lines += [f"## {record['icon'].title()}", '', usage_text(record), '',
                  f"Status: `{record['status']}`. Named owner and reviewer: **pending**.", '',
                  '| Master | Appearance | Visible label | Exceptions | Exact SVG SHA-256 |',
                  '|---|---|---|---|---|']
        for n, appearances in record['sizes'].items():
            for a, cell in appearances.items():
                lines.append(f"| {n} | {a} | {'Required' if cell['visibleLabelRequired'] else 'No additional rule'} | {', '.join(cell['exceptionIds']) or 'None'} | `{cell['geometrySha256']}` |")
        lines += ['']
    (root / 'docs/usage-restrictions.md').write_text('\n'.join(lines)+'\n', encoding='utf-8')
    (root / 'packages/web/usage-data.mjs').write_text(
        '// GENERATED from catalog/restrictions.json.\nexport const usageRecords = '
        + json.dumps(data, separators=(',', ':')) + ';\n', encoding='utf-8')
