# name: Integration Tests

# on:
#   push:
#     branches: [ main, develop, feature/* ]
#   pull_request:
#     branches: [ main, develop ]
#   workflow_dispatch:

# jobs:
#   test:
#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v3
    
#     - name: Setup Flutter
#       uses: subosito/flutter-action@v2
#       with:
#         flutter-version: 'stable'
#         channel: 'stable'
    
#     - name: Install dependencies
#       run: flutter pub get
    
#     - name: Run integration tests
#       run: ./test/run_integration_tests.sh
#       continue-on-error: true
    
#     - name: Upload test results
#       if: always()
#       uses: actions/upload-artifact@v4
#       with:
#         name: test-results
#         path: test-results/
        
#     - name: Comment PR with results
#       if: github.event_name == 'pull_request'
#       uses: actions/github-script@v6
#       with:
#         script: |
#           const fs = require('fs');
#           const testOutput = fs.readFileSync('test-results/summary.txt', 'utf8');
#           github.rest.issues.createComment({
#             issue_number: context.issue.number,
#             owner: context.repo.owner,
#             repo: context.repo.repo,
#             body: `## Integration Test Results\n\`\`\`\n${testOutput}\n\`\`\``
#           })